### ISSUE TITLE
gzip problem

### ISSUE THREAD

**Issue by martinwolff** [ngduc/Thin-PHP-Framework#4]
The header output 

header("Content-Encoding: gzip");

in main_util.php in function outputJson() returns a content encoding error  if gzip is not possible.

**Comment by ngduc** [comment]
I haven't tested this yet, but it's a way to check: (BaseController.php)

```
        require_once $fullpath;
        if(!ob_start("ob_gzhandler")) { // if the browser supports gzip
            ob_start();
            // load extension
            $ctr = new $className();
            $ctr->handle($params);

            $ret = ob_get_contents();
            ob_end_clean();
        } else {
            $ctr = new $className();
            $ctr->handle($params);
        }
```

</code>
Will fix this in the next version.

**Comment by ngduc** [comment]
Talking about gzip,
I have just fixed a problem in "outputJson" function in "main_util.php" using ini_set.
