### ISSUE TITLE
Validation error messages

### ISSUE THREAD

**Issue by martinwolff** [ngduc/Thin-PHP-Framework#5]
The previous error message is shown again on form elements which are validated correctly. 

Check the contact form of the demo and enter only a valid email address and submit it. The email address still has an error message which is the message of the previous invalid  form element.

**Comment by martinwolff** [comment]
I changed in my version in thinphp.js:

// $(formId+' :input[name='+fieldName+'] ~ span.fmsg').html('&nbsp;'+errMsg+'&nbsp;');
// $(formId+' :input[name='+fieldName+'] ~ span.fmsg').fadeIn('slow');

$('#err_' + fieldName).html('&nbsp;'+errMsg+'&nbsp;');
$('#err_' + fieldName).fadeIn('slow');

And in the html form I added an ID attribute which starts with err_ followed by the attributes name:

<span id="err_email" class="fmsg"></span>

**Comment by irtusb** [comment]
good job martinwolff, I ran into the same issue some time ago, thanks for the code

**Comment by irtusb** [comment]
due to github markdown, underscores are not seen put a blank line to separate your lines

**Comment by ngduc** [comment]
Good solution!

btw, I've fixed that error in this commit:
https://github.com/ngduc/Thin-PHP-Framework/commit/a920978bdc5f2fd04d27bfef4f8b427d1aa3b28f

A new version 0.55 has just been released.
Thanks.
