### ISSUE TITLE
/tool/setup-db/index.php give error

### ISSUE THREAD

**Issue by ellisgl** [ngduc/Thin-PHP-Framework#7]
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in C:\UniServer\www\thin\app\model\base\driver\DBPdoMysql.php on line 27

**Comment by ngduc** [comment]
hi ellisgl, this is a known MySql bug, use value 1002 instead that constant.
reference:
http://stackoverflow.com/questions/2510267/zend-framework-undefined-class-constant-mysql-attr-init-command
