### ISSUE TITLE
Webpage "Contact Us" runs into gateway timeout

### ISSUE THREAD

**Issue by martinwolff** [ngduc/Thin-PHP-Framework#9]
Hi,
after I submitted a message on the "contact us" page, I got a timeout. Wanted to ask if you're looing for another developer as I am using the framework for my master thesis at the moment.
Regards,
Martin

**Comment by ngduc** [comment]
Sorry for responding late.
I've been busy with my other project (using TPF) and my work. I've just moved to BayArea.
Glad you are using it & thanks for your report about "Contact us" page. I will fix it today.
Contact me thru: duc java at gmail
Best.
Duc
